apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-world-1
  namespace: '501588116760'
  selfLink: /apis/serving.knative.dev/v1/namespaces/501588116760/services/hello-world-1
  uid: 13672f65-4e2c-49b2-bf38-aec4b267d070
  resourceVersion: AAYJw8EWJ8c
  generation: 5
  creationTimestamp: '2023-11-10T01:02:16.445985Z'
  labels:
    managed-by: gcp-cloud-build-deploy-cloud-run
    gcb-trigger-id: 0f7cf389-75de-4aa1-91d8-31eda7e0b89a
    gcb-trigger-region: global
    commit-sha: 10a8e7049e7f98ae92c87af156e069031fa11ed5
    gcb-build-id: aab417f9-6b40-4d10-b830-82dd8b256300
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/client-name: gcloud
    serving.knative.dev/creator: aruna.australia@gmail.com
    serving.knative.dev/lastModifier: 501588116760-compute@developer.gserviceaccount.com
    run.googleapis.com/client-version: 454.0.0
    run.googleapis.com/operation-id: d126ca6f-da8b-454e-a75b-79c2c7fc318f
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      labels:
        client.knative.dev/nonce: bkgdfmduxr
        managed-by: gcp-cloud-build-deploy-cloud-run
        gcb-trigger-id: 0f7cf389-75de-4aa1-91d8-31eda7e0b89a
        gcb-trigger-region: global
        commit-sha: 10a8e7049e7f98ae92c87af156e069031fa11ed5
        gcb-build-id: aab417f9-6b40-4d10-b830-82dd8b256300
        run.googleapis.com/startupProbeType: Default
      annotations:
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 454.0.0
        autoscaling.knative.dev/maxScale: '100'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 501588116760-compute@developer.gserviceaccount.com
      containers:
      - image: us-central1-docker.pkg.dev/ferrous-store-404700/cloud-run-source-deploy/node-mappings/hello-world-1:10a8e7049e7f98ae92c87af156e069031fa11ed5
        ports:
        - name: http1
          containerPort: 8080
        resources:
          limits:
            cpu: '1'
            memory: 256Mi
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 8080
  traffic:
  - percent: 100
    latestRevision: true
status:
  observedGeneration: 5
  conditions:
  - type: Ready
    status: 'True'
    lastTransitionTime: '2023-11-10T03:17:02.908030Z'
  - type: ConfigurationsReady
    status: 'True'
    lastTransitionTime: '2023-11-10T03:16:50.416066Z'
  - type: RoutesReady
    status: 'True'
    lastTransitionTime: '2023-11-10T03:17:02.991303Z'
  latestReadyRevisionName: hello-world-1-00004-47c
  latestCreatedRevisionName: hello-world-1-00004-47c
  traffic:
  - revisionName: hello-world-1-00004-47c
    percent: 100
    latestRevision: true
  url: https://hello-world-1-6d3c5hapia-uc.a.run.app
  address:
    url: https://hello-world-1-6d3c5hapia-uc.a.run.app
